//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Read.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Read.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- 默认热键设置 --&gt;
        ///&lt;HotKeys&gt;
        ///  &lt;item&gt;
        ///    &lt;KeyCode&gt;Left&lt;/KeyCode&gt;
        ///    &lt;Effect&gt;上一页&lt;/Effect&gt;
        ///    &lt;Details&gt;向左键&lt;/Details&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;KeyCode&gt;Right&lt;/KeyCode&gt;
        ///    &lt;Effect&gt;下一页&lt;/Effect&gt;
        ///    &lt;Details&gt;向右键&lt;/Details&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;KeyCode&gt;Up&lt;/KeyCode&gt;
        ///    &lt;Effect&gt;上一页&lt;/Effect&gt;
        ///    &lt;Details&gt;向上键&lt;/Details&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;KeyCode&gt;Down&lt;/KeyCode&gt;
        ///    &lt;Effect&gt;下一页&lt;/Effect&gt;
        ///    &lt;Details&gt;向下键&lt;/Details&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;KeyCode&gt;Oemti [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultHotKey {
            get {
                return ResourceManager.GetString("DefaultHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--预置配色--&gt;
        ///&lt;PresetColors&gt;
        ///  &lt;item&gt;
        ///    &lt;Name&gt;藏青&lt;/Name&gt;
        ///    &lt;BackColor&gt;#333F50&lt;/BackColor&gt;
        ///    &lt;ForeColor&gt;#B4B5B6&lt;/ForeColor&gt;
        ///    &lt;MessageColor&gt;#FF6347&lt;/MessageColor&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Name&gt;纯白&lt;/Name&gt;
        ///    &lt;BackColor&gt;#FFFFFF&lt;/BackColor&gt;
        ///    &lt;ForeColor&gt;#4B4B4B&lt;/ForeColor&gt;
        ///    &lt;MessageColor&gt;#FF6347&lt;/MessageColor&gt;
        ///&lt;/item&gt;
        ///&lt;/PresetColors&gt; 的本地化字符串。
        /// </summary>
        internal static string DefaultPresetColor {
            get {
                return ResourceManager.GetString("DefaultPresetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!-- 键位编码及备注 --&gt;
        ///&lt;KeyCodes&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;KeyCode&lt;/Key&gt;
        ///    &lt;Value&gt;从键值提取键代码的位屏蔽&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;Modifiers&lt;/Key&gt;
        ///    &lt;Value&gt;从键值提取修饰符的位屏蔽&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;None&lt;/Key&gt;
        ///    &lt;Value&gt;没有按任何键&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;LButton&lt;/Key&gt;
        ///    &lt;Value&gt;鼠标左按钮&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;RButton&lt;/Key&gt;
        ///    &lt;Value&gt;鼠标右按钮&lt;/Value&gt;
        ///  &lt;/item&gt;
        ///  &lt;item&gt;
        ///    &lt;Key&gt;Cancel&lt;/Key&gt;
        ///    &lt;Value&gt;Cancel键&lt;/Value&gt;
        ///  &lt;/item&gt;
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string KeyCodes {
            get {
                return ResourceManager.GetString("KeyCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
